require("plugins.settings.treesitter")
require("plugins.settings.colorscheme")
require("plugins.settings.lualine")
require("plugins.settings.mason")
require("plugins.settings.neotree")
require("plugins.settings.which-key")
require("plugins.settings.lsp")
require("plugins.settings.cmp")
